# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 22:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('cost', models.FloatField(default=10.0)),
                ('deleted', models.BooleanField(default=False)),
                ('link', models.URLField(max_length=30, null=True)),
                ('ulink', models.URLField(max_length=30, null=True)),
                ('dlink', models.URLField(max_length=30, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
