# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 18:44
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('link', models.URLField(max_length=30, null=True)),
                ('ulink', models.URLField(max_length=30, null=True)),
                ('dlink', models.URLField(max_length=30, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=20, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('link', models.URLField(max_length=30, null=True)),
                ('ulink', models.URLField(max_length=30, null=True)),
                ('dlink', models.URLField(max_length=30, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('sku', models.CharField(max_length=10, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('deleted', models.BooleanField(default=False)),
                ('link', models.URLField(max_length=30, null=True)),
                ('ulink', models.URLField(max_length=30, null=True)),
                ('dlink', models.URLField(max_length=30, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple.Store'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simple.Widget'),
        ),
    ]
