def get_users():
    users = {'qa': {'username': 'qa',
                    'password': 'br0k3nc0d3',
                    'email': 'qa@random.org',
                    'is_staff': True,
                    'is_superuser': False,
                    'is_active': True},
             'active': {'username': 'active',
                        'password': 'basicuser',
                        'email': 'active@random.org',
                        'is_staff': False,
                        'is_superuser': False,
                        'is_active': True},
             'staff': {'username': 'staff',
                       'password': 'adminaccess',
                       'email': 'staff@random.org',
                       'is_staff': True,
                       'is_superuser': False,
                       'is_active': True},
             'superuser': {'username': 'superuser',
                           'password': 'fullaccess',
                           'email': 'superuser@random.org',
                           'is_staff': True,
                           'is_superuser': True,
                           'is_active': True},
             'invalid': {'username': 'invalid',
                         'password': 'wrongguess',
                         'email': 'invalid@random.org',
                         'is_staff': False,
                         'is_superuser': False,
                         'is_active': False},
             'view': {'username': 'view',
                      'password': 'readonly',
                      'email': 'view@random.org',
                      'is_staff': False,
                      'is_superuser': False,
                      'is_active': True},
             'add': {'username': 'add',
                      'password': 'write',
                      'email': 'add@random.org',
                      'is_staff': True,
                      'is_superuser': False,
                      'is_active': True},
             'change': {'username': 'change',
                        'password': 'readwrite',
                        'email': 'change@random.org',
                        'is_staff': False,
                        'is_superuser': False,
                        'is_active': True},
             'delete': {'username': 'delete',
                        'password': 'write',
                        'email': 'delete@random.org',
                        'is_staff': False,
                        'is_superuser': False,
                        'is_active': True}}
    return users
